---
- name: wait the cluster is consistent
  pause:
    seconds: 5
  when: not k8s_test

- name: install weavenet
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE=10.200.0.0/16"

- name: check pods
  shell: kubectl get pods -n kube-system
  register: kube_out

- name: testing
  block:
    - name: wait networking is consistent
      pause:
        seconds: 10
      when: not k8s_test

    - name: create two nginx replica deployment
      shell: "kubectl apply -f {{ role_path }}/files/nginx_replicas.yml"

    - name: check if service exists
      shell: kubectl get svc nginx --ignore-not-found -o jsonpath="{.metadata.name}"
      register: service_nginx

    - name: expose deployment as service
      shell: "kubectl expose deployment/nginx"
      when: service_nginx.stdout != "nginx"

    - name: deploy busybox
      shell: "kubectl run busybox --image=radial/busyboxplus:curl --command -- sleep 3600"

    - name: check busybox
      shell: kubectl get pods -l run=busybox -o jsonpath="{.items[0].metadata.name}"
      register: busyb
  when: k8s_test

- name: clean up
  block:
    - name: delete busybox
      shell: kubectl delete pod busybox --force

    - name: delete nginx deploy
      shell: kubectl delete deploy nginx

    - name: delete nginx service
      shell: kubectl delete svc nginx
  when: clean_up