---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: copy nginx configuration
  template:
    src: kubernetes.default.svc.cluster.local.j2
    dest: "/etc/nginx/sites-available/kubernetes.default.svc.cluster.local"
    mode: '0644'

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    state: link
  notify: nginx-restart

- name: check healthz is working
  shell: 'curl -H "Host: kubernetes.default.svc.cluster.local" -i http://127.0.0.1/healthz'
  register: health_check
  when: inventory_hostname == "master-1"

- name: debug health check
  debug:
    msg: "{{ health_check.stdout_lines | to_nice_json }}"
  when: inventory_hostname == "master-1"