---
certificate_path: "k8s-certs"
user_home: "{{ ansible_facts['user_dir'] }}"
etcd_version: "v3.3.5"
k8s_ver: "v1.18.6"
etcd_upgrade: false
k8s_conf_path: "/etc/kubernetes/config"
k8s_lib_path: "/var/lib/kubernetes"
## kept only to check if the order is important
cert_hostname_list: [10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,127.0.0.1,localhost,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local]
cert_hostname: []
remote_user: vagrant
vagrant_dir:
merged_hosts: []
workers:
  - name: node-1
    ip: 192.168.50.21
  - name: node-2
    ip: 192.168.50.22

loadbalancer:
  - name: loadbalancer
    ip: 192.168.50.30

controllers:
  - name: master-1
    ip: 192.168.50.11
  - name: master-2
    ip: 192.168.50.12