---
- name: create containerd directory
  file:
    path: "/etc/containerd"
    state: directory
    mode: '0755'

- name: Create containerd configuration
  template:
    src: config.toml.j2
    dest: "/etc/containerd/config.toml"
    mode: '0644'

- name: Create containerd service
  template:
    src: containerd.service.j2
    dest: "/etc/systemd/system/containerd.service"
    mode: '0644'