---
- name: kube restart
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  listen: kube-restart