---
- name: Generate data encryption
  shell: "head -c 32 /dev/urandom | base64"
  register: random_string

- name: get string
  set_fact:
    encryption_key: "{{ random_string.stdout }}"

- name: Check if key already exists
  stat:
    path: "{{ ansible_facts['user_dir'] }}/{{ certificate_path }}/encryption-config.yaml"
  register: enc_key

- name: Create encryption config file
  template:
    src: encryption-config.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/{{ certificate_path }}/encryption-config.yaml"
    mode: '0644'
  when: not enc_key.stat.exists
