# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

IMAGE_NAME = "ubuntu/xenial64"

configs        = YAML.load_file('../inventory/group_vars/all.yml')
vagrant_config = configs['configs']

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    (1..vagrant_config['number_master']).each do |i|
        config.vm.define "master-#{i}", primary: true do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "192.168.50.#{10+i}"
            master.vm.hostname = "master-#{i}"
        end
    end

    config.vm.define "loadbalancer", primary: true do |loadbalancer|
        loadbalancer.vm.box = IMAGE_NAME
        loadbalancer.vm.network "private_network", ip: "192.168.50.30"
        loadbalancer.vm.hostname = "loadbalancer"
    end
end

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end

    (1..vagrant_config['number_node']).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{20+i}"
            node.vm.hostname = "node-#{i}"
        end
    end
end