IMAGE_NAME = "ubuntu/xenial64"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    (1..N).each do |i|
        config.vm.define "master-#{i}", primary: true do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "192.168.50.#{10+i}"
            master.vm.hostname = "master-#{i}"
        end
    end

    config.vm.define "loadbalancer", primary: true do |loadbalancer|
        loadbalancer.vm.box = IMAGE_NAME
        loadbalancer.vm.network "private_network", ip: "192.168.50.30"
        loadbalancer.vm.hostname = "loadbalancer"
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{20+i}"
            node.vm.hostname = "node-#{i}"
        end
    end
end

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{20+i}"
            node.vm.hostname = "node-#{i}"
        end
    end
end