---
- name: nginx start
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: nginx
  listen: nginx-start
  ignore_errors: "{{ ansible_check_mode }}"

- name: nginx restart
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: nginx
  listen: nginx-restart
  ignore_errors: "{{ ansible_check_mode }}"