---
- name: Set os
  set_fact:
    os_type: "{% if ansible_facts['os_family']|lower == 'darwin' %}darwin{% else %}linux{% endif %}"

- name: Dowload cfssl cfssljson
  get_url:
    url: "{{ cfssl_url }}{{ os_type }}/{{ item }}"
    dest: "{{ local_executable_path }}/{{ item }}"
    mode: '0755'
  become: true
  with_items:
    - cfssl
    - cfssljson

- name: Dowload kubectl
  get_url:
    url: "{{ k8s_url }}{{ os_type }}/amd64/{{ item }}"
    dest: "{{ local_executable_path }}/{{ item }}"
    mode: '0755'
  become: true
  with_items:
    - kubectl