---
- name: local user
  shell: "echo $HOME"
  register: local_user_home
  delegate_to: 127.0.0.1

- name: copy certificates and configuration in common between nodes
  copy:
    src: "{{ local_user_home.stdout }}/{{ certificate_path }}/{{ item }}"
    dest: "/home/{{ remote_user }}/"
    force: no
    mode: '0644'
  with_items:
    - ca.pem
    - kube-proxy.kubeconfig
  when: '"node" in inventory_hostname'

- name: copy certificates and configuration into node
  copy:
    src: "{{ local_user_home.stdout }}/{{ certificate_path }}/{{ item }}"
    dest: "/home/{{ remote_user }}/"
    force: no
    mode: '0644'
  with_items:
    - "{{ inventory_hostname }}-key.pem"
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}.kubeconfig"
  when: '"node" in inventory_hostname'

- name: copy certificates and configuration into master nodes
  copy:
    src: "{{ local_user_home.stdout }}/{{ certificate_path }}/{{ item }}"
    dest: "/home/{{ remote_user }}/"
    force: no
    mode: '0644'
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
    - encryption-config.yaml
  when: '"master" in inventory_hostname'