---
- name: Create merged list
  set_fact:
    merged_hosts: "{{ merged_hosts + [item] }}"
  with_items:
    - "{{ workers }}"
    - "{{ controllers }}"
    - "{{ loadbalancer }}"

- name: Add hosts into system hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    "{{ merged_hosts }}"
  become: true
  when: rewrite_hosts is defined

- name: Vagrant ssh key
  shell: vagrant ssh-config loadbalancer | grep IdentityFile | awk '{print $2}'
  args:
    chdir: ../vagrant
  register: vagrant_ssh_key

- name: check if file exists
  stat:
    path: "{{ inventory_dir }}/vagrant_hosts"
  register: vagrant_hosts

- name: Add hosts to ansible host file
  template:
    src: hosts.j2
    dest: "{{ inventory_dir }}/vagrant_hosts"
  loop:
    "{{ merged_hosts }}"
