---
#- hosts: 127.0.0.1
#  connection: local

- hosts: all
  gather_facts: true
  become: false
  become_method: sudo
  vars_files:
    - "./vars/generic_vars.yml"

  roles:
    #- {role: client, tags: ["client"]}
    - {role: pki, tags: ["pki"]}
    - {role: kube-config, tags: ["config"]}
