---
- hosts: local
  gather_facts: true
  become: false
  become_method: sudo
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yml"

  roles:
    - {role: resolv-hosts, tags: ["hosts"]}
    - {role: client, tags: ["client"]}
    - {role: pki, tags: ["pki"]}
    - {role: kube-config, tags: ["config"]}
    - {role: data-encryption, tags: ["data-encryption"]}

- hosts: all:!local
  gather_facts: true
  become: false
  become_method: sudo

  roles:
    - {role: send-file, tags: ["send"]}

- hosts: masters
  gather_facts: true
  become: true
  become_method: sudo

  roles:
    - {role: install-etcd, tags: ["etcd"]}
    - {role: install-kubernetes, tags: ["kubernetes"]}
    - {role: health-check, tags: ["health-check"]}
    - { role: rbac-kubelet, tags: ["rbac-kubelet"], when: inventory_hostname == "master-1" }

- hosts: loadbalancer
  gather_facts: true
  become: true
  become_method: sudo

  roles:
    - { role: api-loadbalancer, tags: ["api-loadbalancer"] }

- hosts: workers
  gather_facts: true
  become: true
  become_method: sudo

  roles:
    - {role: install-workers, tags: ["install-workers"]}
    - {role: configure-containerd, tags: ["containerd"]}
    - {role: kubelet, tags: ["kubelet"]}
    - {role: kubeproxy, tags: ["kubeproxy"]}

- hosts: local
  gather_facts: true
  become: false
  become_method: sudo

  roles:
    - {role: kubectl, tags: ["kubectl"]}
    - {role: weavenet, tags: ["weavenet"]}
    - {role: dns, tags: ["dns"]}
