---
#- hosts: 127.0.0.1
#  connection: local

- hosts: local
  gather_facts: true
  become: false
  become_method: sudo
  vars_files:
    - "./vars/generic_vars.yml"

  roles:
    - {role: resolv-hosts, tags: ["hosts"]}
    - {role: client, tags: ["client"]}
    - {role: pki, tags: ["pki"]}
    - {role: kube-config, tags: ["config"]}
    - {role: data-encryption, tags: ["data-encryption"]}
    - {role: test, tags: ["test"]}

- hosts: all:!local
  gather_facts: true
  become: false
  become_method: sudo
  vars_files:
    - "./vars/generic_vars.yml"

  roles:
    - {role: send-file, tags: ["send"]}

- hosts: masters
  gather_facts: true
  become: true
  become_method: sudo
  vars_files:
    - "./vars/generic_vars.yml"

  roles:
    - {role: install-etcd, tags: ["etcd"]}
    - {role: install-kubernetes, tags: ["kubernetes"]}
    - {role: health-check, tags: ["health-check"]}

- hosts: master-1
  gather_facts: true
  become: true
  become_method: sudo
  vars_files:
    - "./vars/generic_vars.yml"

  roles:
    - { role: rbac-kubelet, tags: ["rbac-kubelet"] }