---
certificate_path: "../k8s-certs"
user_home: "{{ ansible_facts['user_dir'] }}"
local_executable_path: "/usr/local/bin"
etcd_version: "v3.3.5"
k8s_ver: "v1.18.6"
containerd_ver: "1.3.6"
cni_ver: "0.8.6"
cri_tools_ver: "1.18.0"
etcd_upgrade: true
k8s_test: false
clean_up: false
CIDR: "10.200.0.0/16"
k8s_conf_path: "/etc/kubernetes/config"
k8s_lib_path: "/var/lib/kubernetes"
## kept only to check if the order is important
cert_hostname_list: [10.32.0.1,127.0.0.1,localhost,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local]
cert_hostname: []
remote_user: vagrant
vagrant_dir:
merged_hosts: []

configs:
    vbox_ubuntu_dist: "ubuntu/xenial64" # Currently this cannot be change
    number_node: 2
    number_master: 2
    node_memory: 1024
    controller_memory: 1024
    loadbalancer_memory: 512

workers_list:
  - name: node-1
    ip: 192.168.50.21
    cidr: 10.200.0.0/18
  - name: node-2
    ip: 192.168.50.22
    cidr: 10.200.64.0/18

loadbalancer_list:
  - name: loadbalancer
    ip: 192.168.50.30

controllers_list:
  - name: master-1
    ip: 192.168.50.11
  - name: master-2
    ip: 192.168.50.12

workers: "{{ workers_list[:configs.number_node] }}"

controllers: "{{ controllers_list[:configs.number_master] }}"

loadbalancer: "{{ loadbalancer_list }}"